#Result Codes
const SQLITE_OK                              =   0
const SQLITE_ERROR                           =   1
const SQLITE_INTERNAL                        =   2
const SQLITE_PERM                            =   3
const SQLITE_ABORT                           =   4
const SQLITE_BUSY                            =   5
const SQLITE_LOCKED                          =   6
const SQLITE_NOMEM                           =   7
const SQLITE_READONLY                        =   8
const SQLITE_INTERRUPT                       =   9
const SQLITE_IOERR                           =  10
const SQLITE_CORRUPT                         =  11
const SQLITE_NOTFOUND                        =  12
const SQLITE_FULL                            =  13
const SQLITE_CANTOPEN                        =  14
const SQLITE_PROTOCOL                        =  15
const SQLITE_EMPTY                           =  16
const SQLITE_SCHEMA                          =  17
const SQLITE_TOOBIG                          =  18
const SQLITE_CONSTRAINT                      =  19
const SQLITE_MISMATCH                        =  20
const SQLITE_MISUSE                          =  21
const SQLITE_NOLFS                           =  22
const SQLITE_AUTH                            =  23
const SQLITE_FORMAT                          =  24
const SQLITE_RANGE                           =  25
const SQLITE_NOTADB                          =  26
const SQLITE_NOTICE                          =  27
const SQLITE_WARNING                         =  28
const SQLITE_ROW                             = 100
const SQLITE_DONE                            = 101

#Database Connection Configuration Options
const SQLITE_DBCONFIG_MAINDBNAME            = 1000
const SQLITE_DBCONFIG_LOOKASIDE             = 1001
const SQLITE_DBCONFIG_ENABLE_FKEY           = 1002
const SQLITE_DBCONFIG_ENABLE_TRIGGER        = 1003
const SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER = 1004
const SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION = 1005
const SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE      = 1006
const SQLITE_DBCONFIG_ENABLE_QPSG           = 1007
const SQLITE_DBCONFIG_TRIGGER_EQP           = 1008
const SQLITE_DBCONFIG_MAX                   = 1008

#Flags For File Open Operations
const SQLITE_OPEN_READONLY            = 0x00000001
const SQLITE_OPEN_READWRITE           = 0x00000002
const SQLITE_OPEN_CREATE              = 0x00000004
const SQLITE_OPEN_URI                 = 0x00000040
const SQLITE_OPEN_MEMORY              = 0x00000080
const SQLITE_OPEN_NOMUTEX             = 0x00008000
const SQLITE_OPEN_FULLMUTEX           = 0x00010000
const SQLITE_OPEN_SHAREDCACHE         = 0x00020000
const SQLITE_OPEN_PRIVATECACHE        = 0x00040000
